version: '3.9'
services:
  mysql_container:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: gualdina2018
      MYSQL_DATABASE: store

